# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
workflows:
  sample:
    jobs:
      - welcome/run
