# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
docker-default: &docker-node
  docker:
    - image: circleci/node:14
jobs:
  build:
    <<: *docker-node
    steps:
      - checkout
      - run: npm i
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *docker-node
    steps:
      - run:
          name: Lint
          command: npm run test
  analyse:
    <<: *docker-node
    steps:
      - run:
          name: Lint
          command: npm audit
workflows:
  sample:
    jobs:
      - welcome/run
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
