# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
docker-default: &docker-node
  docker:
    - image: circleci/node:14
jobs:
  build:
    <<: *docker-node
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: node_modules
          paths:
            - /src/node_modules
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *docker-node
    steps:
      - run: ls
      - checkout
      - restore_cache:
          keys:
            - node_modules
      - run: npm i
      - run:
          name: Test
          command: npm run test
  analyse:
    <<: *docker-node
    steps:
      - checkout
      - run:
          name: Audit
          command: npm audit
  fix:
    <<: *docker-node
    steps:
      - checkout
      - run:
          name: Fix
          command: npm audit fix
      - checkout
      - save_cache:
          key: node_modules
          paths:
            - /src/node_modules
workflows:
  sample:
    jobs:
      - welcome/run
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - fix:
          requires:
            - build
      - analyse:
          requires:
            - test
            - fix
